# Generated by Django 4.2.2 on 2023-06-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=4)),
                ('summer', models.CharField(blank=True, max_length=4)),
                ('autumn', models.CharField(blank=True, max_length=4)),
                ('spring', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('other_titles', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('New', 'Новый'), ('Pending', 'В обработке'), ('Accepted', 'Принято'), ('Rejected', 'Не принято')], default='New', max_length=8)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_FSTR.coordinates')),
                ('levels', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='app_FSTR.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_FSTR.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_FSTR.mountain')),
            ],
        ),
    ]
