# Generated by Django 4.2.2 on 2023-06-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_FSTR.user'),
        ),
    ]
