# Generated by Django 4.2.2 on 2023-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0008_alter_mountain_beauty_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='beauty_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
