# Generated by Django 4.2.2 on 2023-06-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0009_alter_mountain_beauty_title_alter_mountain_title'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinates',
            table='mountain_coordinates',
        ),
        migrations.AlterModelTable(
            name='images',
            table='mountain_images',
        ),
        migrations.AlterModelTable(
            name='level',
            table='mountain_level',
        ),
        migrations.AlterModelTable(
            name='mountain',
            table='mountain_mountain',
        ),
        migrations.AlterModelTable(
            name='user',
            table='mountain_user',
        ),
    ]
