# Generated by Django 4.2.2 on 2023-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0010_alter_coordinates_table_alter_images_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterModelTable(
            name='coordinates',
            table=None,
        ),
        migrations.AlterModelTable(
            name='images',
            table=None,
        ),
        migrations.AlterModelTable(
            name='level',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mountain',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
