# Generated by Django 4.2.2 on 2023-06-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0014_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='mountain',
        ),
    ]
