# Generated by Django 4.2.2 on 2023-06-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0016_alter_images_options_images_mountain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='mountain',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения'),
        ),
    ]
