# Generated by Django 4.2.2 on 2023-06-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0017_remove_images_mountain_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='mountain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_FSTR.mountain'),
        ),
    ]
