# Generated by Django 4.2.2 on 2023-06-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0018_images_mountain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
