# Generated by Django 4.2.2 on 2023-06-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0019_rename_image_images_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='imagee',
        ),
    ]
