# Generated by Django 4.2.2 on 2023-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0020_rename_images_images_imagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения'),
        ),
    ]
