# Generated by Django 4.2.2 on 2023-06-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0021_mountain_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='created',
        ),
        migrations.RemoveField(
            model_name='images',
            name='imagee',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
