# Generated by Django 4.2.2 on 2023-06-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0022_remove_images_created_remove_images_imagee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
