# Generated by Django 4.2.2 on 2023-06-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_FSTR', '0023_images_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinates',
            options={},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mountain',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
